name: Build All
on: [workflow_dispatch]
jobs:
  build_android:
    uses: ./.github/workflows/build_android.yml
  build_ios:
    uses: ./.github/workflows/build_ios.yml
# TODO investigate failures: build_linux:
# TODO investigate failures:   uses: ./.github/workflows/build_linux.yml
  build_osx:
    uses: ./.github/workflows/build_osx.yml
# TODO investigate failures  build_windows:
# TODO investigate failures    uses: ./.github/workflows/build_windows.yml
