name: Build Linux
on: [workflow_call, workflow_dispatch]
jobs:
  build_linux:
    timeout-minutes: 30
    strategy:
      matrix:
        build-type: [MinSizeRel]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 ## only used for its github action scripts, vcpkg is what pulls it in as an actual dependency
        with:
          repository: heroiclabs/nakama-cpp
          path: nakama-cpp
          ref: 3164abbae8156f2e989c4f18219958988a24b448
      - uses: actions/checkout@v3
        with:
          path: nakama-cocos2d-x
      - uses: ./nakama-cpp/.github/actions/setup-ubuntu
      - uses: ./nakama-cpp/.github/actions/setup-vcpkg
        with:
          github_token: ${{ secrets.github_token }}
          vcpkg-path: vcpkg
      - uses: ./nakama-cpp/.github/actions/build-library-and-upload
        with:
          nakama-cpp-path: nakama-cocos2d-x
          preset: linux-amd64
          build-type: ${{ matrix.build-type }}
      - if: failure()
        uses: ./nakama-cpp/.github/actions/handle-failure
        with:
          nakama-cpp-path: nakama-cocos2d-x
          vcpkg-path: vcpkg
